#Expyriment 0.9.0 (Python 2.7.10), .xpe-file, coding: cp1252
#date: Wed May 17 2017 17:38:43
#sha1: a892ee
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: ('Windows', 'Gnolo', '8', '6.2.9200', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
624,Picture,loaded,./img\configuration_1.jpg
653,Picture,loaded,./img\configuration_2.jpg
681,Picture,loaded,./img\configuration_3.jpg
706,Picture,loaded,./img\configuration_4.jpg
733,Picture,loaded,./img\configuration_5.jpg
1434,design,log,
#design: #exp: Configural processing
#design: #dvn: block,trial,RT,fixcross_color
#design: block_cnt,block_id,trial_cnt,trial_id,fixcross_color
#design: 0,0,0,0,G
#design: 0,0,1,3,G
#design: 0,0,2,1,G
#design: 0,0,3,2,G
#design: 0,0,4,4,G
1434,design,logged,
1434,Experiment,started
1436,Stimulus,presented,7
2122,Keyboard,received,53,wait
2122,Stimulus,presented,0
2223,Stimulus,presented,2
2224,stderr,received,'Traceback (most recent call last):'
2224,stderr,received,'  File ".\\config_fmri.py", line 75, in <module>'
2225,stderr,received,'    duration = IMAG_DURATION)'
2226,stderr,received,"TypeError: check() got an unexpected keyword argument 'duration'"
